services:
  booking:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking
    restart: always
    ports:
      - '4001:3000'
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads   # <-- Add this line
    networks:
      - monorepo-network

  booking-batch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking-batch
    restart: unless-stopped
    ports:
      - '4002:3001'
    command: npm run start:prod:batch
    env_file:
      - .env
    networks:
      - monorepo-network

networks:
  monorepo-network:
    driver: bridge
