services:
  booking:
    container_name: booking
    restart: always
    image: node:20.10.0
    ports:
      - '4001:3000'
    volumes:
      - ./:/usr/src/booking
    working_dir: /usr/src/booking
    networks:
      - monorepo-network
    command: bash -c "rm -rf dist && npm install && npm run build && npm run start:prod"

  booking-batch:
    container_name: booking-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - '4002:3001'
    volumes:
      - ./:/usr/src/booking
    working_dir: /usr/src/booking
    networks:
      - monorepo-network
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
